server:
  port: 8082

# 应用名称
spring:
  application:
    name: newbee-cloud-shopcart-service
  cloud:
    nacos:
      discovery:
        server-addr: 1.14.244.42:8848
#      username: nacos
#      password: nacos

    # 默认为8719，作用：启动一个HTTP客户端服务，该服务将于Sentinel控制台进行数据交互。如果该端口被占用，则从8719依次+1扫描
    sentinel:
      transport:
        port: 8719
        # 指定Sentinel控制台地址
        dashboard: localhost:8090

  # datasource config
  datasource:
    url: jdbc:mysql://localhost:3306/test_distribution_cart_db?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: li970511

## seata config
seata:
  #是否开启自动配置
  enabled: true
  application-id: shopcart-server
  #事务分组配置
  tx-service-group: test_save_order_group
  service:
    vgroup-mapping:
      test_save_order_group: default
  #连接Nacos服务中心的配置信息
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 1.14.244.42:8848
      username: nacos
      password: nacos
      group: DEFAULT_GROUP
      cluster: default

# 开启open feign debug级别日志
#logging:
#  level: debug
